baseURL = "https://00sk0.github.io/blog/"
languageCode = "jp"
title = "sk0's blog"
theme = "sk0"
canonifyurls = true
hasCJKLanguage = true
summaryLength = 70
pygmentsCodeFences = true
enableGitInfo = true
[params]
  author = "sk0"

# canonifyurls = true
